import java.util.HashMap;

class GetChampNameBy extends HashMap<String, String> {
	private static final long serialVersionUID = -5254258419553019637L;
	private static GetChampNameBy instance = null;
	public static String id(int id){
		return GetChampNameBy.id(Integer.toString(id));
	}
	public static String id(String id){
		if(instance == null)
			load();
		return instance.get(id) == null? "" + id : instance.get(id);
	}

	private static void load() {
		instance = new GetChampNameBy();
		instance.put("266", "Aatrox");
		instance.put("103", "Ahri");
		instance.put("84", "Akali");
		instance.put("12", "Alistar");
		instance.put("32", "Amumu");
		instance.put("34", "Anivia");
		instance.put("1", "Annie");
		instance.put("22", "Ashe");
		instance.put("268", "Azir");
		instance.put("432", "Bard");
		instance.put("53", "Blitzcrank");
		instance.put("63", "Brand");
		instance.put("201", "Braum");
		instance.put("51", "Caitlyn");
		instance.put("69", "Cassiopeia");
		instance.put("31", "Cho'Gath");
		instance.put("42", "Corki");
		instance.put("122", "Darius");
		instance.put("131", "Diana");
		instance.put("36", "Dr. Mundo");
		instance.put("119", "Draven");
		instance.put("60", "Elise");
		instance.put("28", "Evelynn");
		instance.put("81", "Ezreal");
		instance.put("9", "Fiddlesticks");
		instance.put("114", "Fiora");
		instance.put("105", "Fizz");
		instance.put("3", "Galio");
		instance.put("41", "Gangplank");
		instance.put("86", "Garen");
		instance.put("150", "Gnar");
		instance.put("79", "Gragas");
		instance.put("104", "Graves");
		instance.put("120", "Hecarim");
		instance.put("74", "Heimerdinger");
		instance.put("39", "Irelia");
		instance.put("40", "Janna");
		instance.put("59", "Jarvan IV");
		instance.put("24", "Jax");
		instance.put("126", "Jayce");
		instance.put("222", "Jynx");
		instance.put("429", "Kalista");
		instance.put("43", "Karma");
		instance.put("30", "Karthus");
		instance.put("38", "Kassadin");
		instance.put("55", "Katarina");
		instance.put("10", "Kayle");
		instance.put("85", "Kennen");
		instance.put("121", "Kha'Zix");
		instance.put("96", "Kog'Maw");
		instance.put("7", "LeBlanc");
		instance.put("64", "Lee Sin");
		instance.put("89", "Leona");
		instance.put("127", "Lissandra");
		instance.put("236", "Lucian");
		instance.put("117", "Lulu");
		instance.put("99", "Lux");
		instance.put("54", "Malphite");
		instance.put("90", "Malzahar");
		instance.put("57", "Maokai");
		instance.put("11", "Master Yi");
		instance.put("21", "Miss Fortune");
		instance.put("82", "Mordekaiser");
		instance.put("25", "Morgana");
		instance.put("267", "Nami");
		instance.put("75", "Nasus");
		instance.put("111", "Nautilus");
		instance.put("76", "Nidalee");
		instance.put("56", "Nocturne");
		instance.put("20", "Nunu");
		instance.put("2", "Olaf");
		instance.put("61", "Orianna");
		instance.put("80", "Pantheon");
		instance.put("78", "Poppy");
		instance.put("133", "Quinn");
		instance.put("33", "Rammus");
		instance.put("421", "Rek'Sai");
		instance.put("58", "Renekton");
		instance.put("107", "Renga");
		instance.put("92", "Riven");
		instance.put("68", "Rumble");
		instance.put("13", "Ryze");
		instance.put("113", "Sejuani");
		instance.put("35", "Shaco");
		instance.put("98", "Shen");
		instance.put("102", "Shyvana");
		instance.put("27", "Singed");
		instance.put("14", "Sion");
		instance.put("15", "Sivir");
		instance.put("72", "Skarner");
		instance.put("37", "Sona");
		instance.put("16", "Soraka");
		instance.put("50", "Swain");
		instance.put("134", "Syndra");
		instance.put("91", "Talon");
		instance.put("44", "Taric");
		instance.put("17", "Teemo");
		instance.put("412", "Thresh");
		instance.put("18", "Tristana");
		instance.put("48", "Trundle");
		instance.put("23", "Tryndamere");
		instance.put("4", "Twisted Fate");
		instance.put("29", "Twitch");
		instance.put("67", "Udyr");
		instance.put("6", "Urgot");
		instance.put("110", "Varus");
		instance.put("67", "Vayne");
		instance.put("45", "Veigar");
		instance.put("161", "Vel'Koz");
		instance.put("254", "Vi");
		instance.put("112", "Viktor");
		instance.put("8", "Vladimir");
		instance.put("106", "Volibear");
		instance.put("19", "Warwick");
		instance.put("62", "Wukong");
		instance.put("101", "Xerath");
		instance.put("5", "Xin Zhao");
		instance.put("157", "Yasuo");
		instance.put("83", "Yorick");
		instance.put("154", "Zac");
		instance.put("238", "Zed");
		instance.put("115", "Ziggs");
		instance.put("26", "Zilean");
		instance.put("143", "Zyra");
		instance.put("77", "Udyr");
	}

}
